# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f96e294627cf1e044fb2d0c6068b13ba181315c06f0c165591b21881e73d095b344f06c2fe7f9a9a29d1d6d22bf7805ab3d58c2c92ce6705592655e426cd72f6

test:
  secret_key_base: 7b4f80746e70d4bbde7bb012220b582ec109e9aa09e7cd8eb3a1d31e01649375e24404863522532991427584e684fdcee6f9a344c4f7a0147b91dbd1ff77f2d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
